#!/usr/bin/env python3
"""
Analyze CSV files generated by sweep.sh.
Averages the 'generate' stage time_s across runs for each PROMPT_MODE,
and outputs a summary table comparing PyTorch (_base) vs STeP-codegen (_codegen).
"""

import csv
import os
import sys

PROMPT_MODES = [
    "p_mid_gen_short",
    "p_mid_gen_long",
    "p_long_gen_short",
    "p_long_gen_long",
]

RUNS = 3


def read_generate_time(filepath):
    """Return (prompt_token_len, max_new_tokens, time_s) for the 'generate' row."""
    with open(filepath, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row["stage"] == "generate":
                return (
                    int(row["prompt_token_len"]),
                    int(row["max_new_tokens"]),
                    float(row["time_s"]),
                )
    raise ValueError(f"No 'generate' row found in {filepath}")


def average_runs(mode, postfix, runs, csv_dir):
    times = []
    prompt_token_len = None
    max_new_tokens = None
    for i in range(1, runs + 1):
        filename = f"{mode}_{postfix}_{i}.csv"
        filepath = os.path.join(csv_dir, "logs", filename)
        if not os.path.exists(filepath):
            print(f"Warning: {filepath} not found, skipping.", file=sys.stderr)
            continue
        ptl, mnt, t = read_generate_time(filepath)
        prompt_token_len = ptl
        max_new_tokens = mnt
        times.append(t)
    if not times:
        return prompt_token_len, max_new_tokens, None
    return prompt_token_len, max_new_tokens, sum(times) / len(times)


def main():
    csv_dir = os.path.dirname(os.path.abspath(__file__))

    rows = []
    for mode in PROMPT_MODES:
        ptl_b, mnt_b, avg_base = average_runs(mode, "base", RUNS, csv_dir)
        ptl_c, mnt_c, avg_codegen = average_runs(mode, "codegen", RUNS, csv_dir)

        prompt_token_len = ptl_b or ptl_c
        max_new_tokens = mnt_b or mnt_c
        rows.append((prompt_token_len, max_new_tokens, avg_base, avg_codegen))

    # Write output CSV
    output_path = os.path.join(csv_dir, "sweep_summary.csv")
    with open(output_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["prompt_token_len", "max_new_tokens", "PyTorch (s)", "STeP-codegen (s)", "Speedup"])
        for ptl, mnt, avg_b, avg_c in rows:
            speedup = round(avg_b / avg_c, 2) if avg_b is not None and avg_c else None
            writer.writerow([ptl, mnt,
                             round(avg_b, 2) if avg_b is not None else None,
                             round(avg_c, 2) if avg_c is not None else None,
                             speedup])

    # Print reader-friendly table
    header = f"{'prompt_token_len':<18}{'max_new_tokens':<16}{'PyTorch (s)':<14}{'STeP-codegen (s)':<16}{'Speedup':<10}"
    print(header)
    print("-" * len(header))
    for ptl, mnt, avg_b, avg_c in rows:
        base_str = f"{avg_b:.2f}" if avg_b is not None else "N/A"
        codegen_str = f"{avg_c:.2f}" if avg_c is not None else "N/A"
        speedup = avg_b / avg_c if avg_b is not None and avg_c else None
        speedup_str = f"{speedup:.2f}" if speedup is not None else "N/A"
        print(f"{str(ptl):<18}{str(mnt):<16}{base_str:<14}{codegen_str:<16}{speedup_str:<10}")

    print(f"\nSaved to: {output_path}")


if __name__ == "__main__":
    main()
